import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  safelist: [
    'bg-rs-primary',
    'bg-rs-secondary',
    'bg-rs-secondary-container',
    'bg-green-500',
    'text-rs-on-secondary-container',
    'text-orange-400',
    'text-red-400',
    'bg-rs-surface-container-lowest',
    'bg-orange-950',
    'bg-red-950',
    'bg-rs-surface',
    'bg-transparent',
    'bg-green-900/60',
    'text-green-400',
    'bg-rs-error-container',
    'text-rs-on-error-container',
    'bg-rs-surface-container-highest',
    'text-rs-on-surface-variant',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        rs: {
          'surface': '#18120a',
          'surface-dim': '#18120a',
          'surface-bright': '#3f382e',
          'surface-container-lowest': '#130d06',
          'surface-container-low': '#211b12',
          'surface-container': '#251f16',
          'surface-container-high': '#302920',
          'surface-container-highest': '#3b342a',
          'on-surface': '#ede1d3',
          'on-surface-variant': '#d5c4ae',
          'inverse-surface': '#ede1d3',
          'inverse-on-surface': '#362f26',
          'outline': '#9e8e7a',
          'outline-variant': '#514534',
          'surface-tint': '#ffba41',
          'primary': '#ffba41',
          'on-primary': '#432c00',
          'primary-container': '#d4930a',
          'on-primary-container': '#4b3100',
          'inverse-primary': '#7f5600',
          'secondary': '#6bd8cb',
          'on-secondary': '#003732',
          'secondary-container': '#29a195',
          'on-secondary-container': '#00302b',
          'tertiary': '#96ccff',
          'on-tertiary': '#003353',
          'tertiary-container': '#47a6ef',
          'on-tertiary-container': '#00395c',
          'error': '#ffb4ab',
          'on-error': '#690005',
          'error-container': '#93000a',
          'on-error-container': '#ffdad6',
          'primary-fixed': '#ffddaf',
          'primary-fixed-dim': '#ffba41',
          'on-primary-fixed': '#281800',
          'on-primary-fixed-variant': '#614000',
          'secondary-fixed': '#89f5e7',
          'secondary-fixed-dim': '#6bd8cb',
          'on-secondary-fixed': '#00201d',
          'on-secondary-fixed-variant': '#005049',
          'tertiary-fixed': '#cee5ff',
          'tertiary-fixed-dim': '#96ccff',
          'on-tertiary-fixed': '#001d32',
          'on-tertiary-fixed-variant': '#004a76',
          'background': '#18120a',
          'on-background': '#ede1d3',
          'surface-variant': '#3b342a'
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        danger: {
          DEFAULT: "hsl(var(--danger))",
          foreground: "hsl(var(--danger-foreground))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        'unit-xs': '4px',
        'unit-sm': '8px',
        'unit-md': '12px',
        'unit-base': '16px',
        'unit-lg': '20px',
        'unit-xl': '24px',
      },
      fontSize: {
        'rs-display-2xl': ['30px', { lineHeight: '38px', fontWeight: '700' }],
        'rs-headline-xl': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'rs-title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'rs-subheader-md': ['17px', { lineHeight: '24px', fontWeight: '500' }],
        'rs-body-base': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'rs-caption-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'rs-helper-xs': ['11px', { lineHeight: '16px', fontWeight: '500' }],
        'rs-data-mono-base': ['15px', { lineHeight: '20px', fontWeight: '500' }],
        'rs-data-mono-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
