-- Migration to support offline user creation sync

CREATE TABLE IF NOT EXISTS public.offline_users (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  role TEXT NOT NULL,
  store_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS so the Sync Engine can insert into it
ALTER TABLE public.offline_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Masters can sync offline users"
ON public.offline_users
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.user_roles ur 
    WHERE ur.user_id = auth.uid() AND ur.role = 'master'
  )
);

CREATE OR REPLACE FUNCTION public.sync_offline_user_to_auth()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert into auth.users using the bcrypt hash
  -- Notice we set the id explicitly so it matches the local bridge UUID
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = NEW.id) THEN
    INSERT INTO auth.users (
      id,
      instance_id,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at,
      role,
      aud,
      confirmation_token
    ) VALUES (
      NEW.id,
      '00000000-0000-0000-0000-000000000000',
      NEW.email,
      NEW.password_hash, -- bcrypt hash generated by local bridge
      now(),
      '{"provider":"email","providers":["email"]}',
      jsonb_build_object('full_name', NEW.full_name),
      NEW.created_at,
      NEW.updated_at,
      'authenticated',
      'authenticated',
      ''
    );

    -- Also insert the user role so they have the correct permissions
    INSERT INTO public.user_roles (id, user_id, role, store_id, created_at)
    VALUES (gen_random_uuid(), NEW.id, NEW.role, NEW.store_id, now())
    ON CONFLICT DO NOTHING;
    
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_offline_user_inserted ON public.offline_users;
CREATE TRIGGER on_offline_user_inserted
  AFTER INSERT ON public.offline_users
  FOR EACH ROW EXECUTE FUNCTION public.sync_offline_user_to_auth();
