import { env } from '../env.js';
import type { JournalOutcome, JournalResolution } from '../db/repositories/sync_journal.repo.js';

/**
 * ─────────────────────────────────────────────────────────────────────────
 *  CONDITIONAL WRITES AGAINST POSTGREST
 * ─────────────────────────────────────────────────────────────────────────
 *
 * Everything used to go out as
 *     POST /rest/v1/<table>   Prefer: resolution=merge-duplicates
 * which is an unconditional upsert on the primary key: every field in the
 * payload overwrites the cloud row, unconditionally, forever. `base_version`
 * was captured on every outbox entry and never once read. Conflict detection
 * did not exist - not "was weak", did not exist - and the failure mode was
 * silent: a March snapshot of a product landed on a June edit, stamped today,
 * with nothing anywhere recording that a value had been destroyed.
 *
 * For value-like entities this module replaces that with a compare-and-swap:
 *
 *     PATCH /rest/v1/<table>?id=eq.<id>&version=eq.<base_version>
 *
 * PostgREST turns those filters into the UPDATE's WHERE clause, so the write
 * lands only if the cloud row is still exactly where this device last saw it.
 * With `Prefer: return=representation` the response body is the set of rows
 * actually updated, so an empty array is an unambiguous "zero rows affected"
 * - a CONFLICT, not an error, and the difference matters enormously: an error
 * gets retried, a conflict must not be.
 *
 * ── Where the version number comes from, and why it is the client's ──
 *
 * `version` is incremented locally, in the same UPDATE that changes the row
 * (`SET ... version = version + 1`), and the new value is sent in the PATCH
 * body while the old one goes in the filter. It is NOT generated by the
 * server. Three reasons:
 *
 *  1. A till is expected to run for days with no connectivity at all. A
 *     server-assigned version simply does not exist during that time, so
 *     `base_version` - the thing that makes a stale write detectable - could
 *     not be captured at the moment of the edit, which is the only moment it
 *     is knowable.
 *  2. A server-side trigger that bumped the version on every UPDATE would
 *     break the scheme outright: this device's own PATCH would be re-bumped
 *     to a number it does not know, so its NEXT base_version could never
 *     match and every subsequent write would report a false conflict.
 *  3. It keeps the cloud dumb. `version` is an opaque token that changes on
 *     every write; the compare-and-swap needs nothing more than that.
 *
 * The honest limitation of this choice: versions from different devices are
 * comparable for *identity*, not for *ordering*. Cloud version 7 does not
 * mean "newer than 6" if 6 came from another till. The version answers "did
 * anything change since I looked", never "who is more recent". That is why
 * resolution is a separate, recorded decision rather than an automatic
 * numeric comparison, and why the journal stores both clocks and the remote
 * snapshot.
 *
 * ── Degrading safely before the migration lands ──
 *
 * The cloud `products`/`stores`/`suppliers` tables do not have a `version`
 * column until 20260729120000_sync_conflict_journal.sql is applied. Sending
 * `version=eq.4` to a table without the column is a hard 400 that would fail
 * every product push - i.e. the currently working path would break the moment
 * this code shipped. So the column is probed once per table per process and,
 * when it is absent, writes fall back to exactly the old blind upsert and are
 * journalled as `applied_unguarded`. The app keeps working before the
 * migration, gets real conflict detection after it, and the journal records
 * unambiguously which of the two was in force for every single row.
 */

export interface SupabaseWriteResult {
  outcome: JournalOutcome;
  resolution?: JournalResolution | null;
  httpStatus: number | null;
  serverTs: string | null;
  error?: string | null;
  remoteBefore?: Record<string, unknown> | null;
  remoteVersion?: number | null;
  /** True when the entry should be retried later (transport/server errors). */
  retryable: boolean;
}

const baseHeaders = (): Record<string, string> => ({
  apikey: env.supabaseServiceKey,
  Authorization: `Bearer ${env.supabaseServiceKey}`,
  'Content-Type': 'application/json',
});

const upsertHeaders = (): Record<string, string> => ({
  ...baseHeaders(),
  Prefer: 'resolution=merge-duplicates',
});

const representationHeaders = (): Record<string, string> => ({
  ...baseHeaders(),
  Prefer: 'return=representation',
});

const serverTimeOf = (res: Response): string | null => {
  const date = res.headers.get('date');
  if (!date) return null;
  const parsed = new Date(date);
  return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString();
};

/**
 * Does this cloud table have a `version` column?
 *
 * Probed with a zero-row select rather than assumed, cached for the lifetime
 * of the process. `null` means "not determined yet"; a failed probe is cached
 * as `false` for a short while only, so that a transient network failure at
 * start-up does not pin the whole process into unguarded mode for its entire
 * life.
 */
const versionSupport = new Map<string, { supported: boolean; checkedAt: number }>();
const PROBE_TTL_MS = 5 * 60 * 1000;

export const supportsVersionColumn = async (table: string): Promise<boolean> => {
  const cached = versionSupport.get(table);
  if (cached && (cached.supported || Date.now() - cached.checkedAt < PROBE_TTL_MS)) {
    return cached.supported;
  }
  try {
    const res = await fetch(`${env.supabaseUrl}/rest/v1/${table}?select=version&limit=1`, {
      headers: baseHeaders(),
    });
    const supported = res.ok;
    if (!res.ok) {
      // Drain the body so the connection is reusable, and keep the reason
      // out of the hot path's logs - a missing column here is expected
      // before the migration, not an incident.
      await res.text().catch(() => '');
    }
    versionSupport.set(table, { supported, checkedAt: Date.now() });
    return supported;
  } catch {
    versionSupport.set(table, { supported: false, checkedAt: Date.now() });
    return false;
  }
};

/** Test seam: lets the simulation harness assert both code paths. */
export const __setVersionSupport = (table: string, supported: boolean) => {
  versionSupport.set(table, { supported, checkedAt: Date.now() });
};

/**
 * Columns each cloud table actually has, read once from PostgREST's OpenAPI
 * document and cached.
 *
 * Why this exists: the local schema is a SUPERSET of the cloud's, and the two
 * drift per project. The local products table carries the shop's price tiers
 * (selling_price_2/3/4, wholesale_price_ttc) plus merchandising fields; one
 * cloud project has them, another does not. Sending a column the target lacks
 * makes PostgREST reject the WHOLE row, so a single schema gap would stop that
 * record syncing entirely.
 *
 * Previously the payload map dodged this by hardcoding a list that omitted
 * every tier column - which is precisely why the shop's wholesale prices were
 * never backed up anywhere. Probing instead means the payload can name every
 * column it would like to send, and each project receives exactly the subset
 * it can store. The day the missing columns are added by migration, the data
 * starts flowing on the next push with no code change and no redeploy.
 *
 * The OpenAPI document is used rather than sampling a row because it is
 * authoritative for empty tables too.
 */
const columnCache = new Map<string, { columns: Set<string>; checkedAt: number }>();

export const cloudColumnsFor = async (table: string): Promise<Set<string> | null> => {
  const cached = columnCache.get(table);
  if (cached && Date.now() - cached.checkedAt < PROBE_TTL_MS) return cached.columns;
  try {
    const res = await fetch(`${env.supabaseUrl}/rest/v1/`, { headers: baseHeaders() });
    if (!res.ok) {
      await res.text().catch(() => '');
      return null;
    }
    const spec = (await res.json()) as {
      definitions?: Record<string, { properties?: Record<string, unknown> }>;
    };
    const props = spec?.definitions?.[table]?.properties;
    if (!props) return null;
    const columns = new Set(Object.keys(props));
    columnCache.set(table, { columns, checkedAt: Date.now() });
    return columns;
  } catch {
    // Unknown (offline, or an unexpected response shape) - callers send the
    // payload unchanged rather than guessing a subset and silently dropping
    // fields the cloud may well accept.
    return null;
  }
};

/**
 * Drop keys the target table cannot store. A null probe result means "unknown",
 * in which case nothing is filtered.
 */
export const filterToCloudColumns = async (
  table: string,
  payload: Record<string, unknown>
): Promise<Record<string, unknown>> => {
  const columns = await cloudColumnsFor(table);
  if (!columns) return payload;
  const filtered: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(payload)) {
    if (columns.has(k)) filtered[k] = v;
  }
  // Never send an empty object - if the probe disagrees this badly with the
  // payload, something is wrong with the probe, not the data.
  return Object.keys(filtered).length > 0 ? filtered : payload;
};

/** Test seam. */
export const __setCloudColumns = (table: string, columns: string[]) => {
  columnCache.set(table, { columns: new Set(columns), checkedAt: Date.now() });
};

const isMissingTable = (status: number, body: string): boolean =>
  status === 404 ||
  body.includes('PGRST205') ||
  /relation .* does not exist/i.test(body) ||
  /Could not find the table/i.test(body);

const isDuplicateKey = (status: number, body: string): boolean =>
  status === 409 || body.includes('23505') || /duplicate key value/i.test(body);

const fetchRemoteRow = async (
  table: string,
  id: string
): Promise<{ row: Record<string, unknown> | null; ok: boolean }> => {
  try {
    const res = await fetch(
      `${env.supabaseUrl}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}&limit=1`,
      { headers: baseHeaders() }
    );
    if (!res.ok) {
      await res.text().catch(() => '');
      return { row: null, ok: false };
    }
    const rows = (await res.json()) as Record<string, unknown>[];
    return { row: rows.length > 0 ? rows[0] : null, ok: true };
  } catch {
    return { row: null, ok: false };
  }
};

/**
 * The old behaviour, kept verbatim for ledger entities and for value entities
 * whose cloud table has no version column yet.
 */
export const upsertUnconditional = async (
  table: string,
  payload: Record<string, unknown>,
  outcomeWhenApplied: JournalOutcome
): Promise<SupabaseWriteResult> => {
  try {
    // Send only columns this cloud table actually has - see cloudColumnsFor.
    const safePayload = await filterToCloudColumns(table, payload);
    const res = await fetch(`${env.supabaseUrl}/rest/v1/${table}`, {
      method: 'POST',
      headers: upsertHeaders(),
      body: JSON.stringify([safePayload]),
    });
    const serverTs = serverTimeOf(res);
    if (res.ok) {
      return { outcome: outcomeWhenApplied, httpStatus: res.status, serverTs, retryable: false };
    }
    const body = await res.text().catch(() => res.statusText);
    if (isMissingTable(res.status, body)) {
      return {
        outcome: 'skipped',
        resolution: 'remote_table_missing',
        httpStatus: res.status,
        serverTs,
        error: `Table "${table}" does not exist in Supabase yet: ${body.slice(0, 500)}`,
        retryable: false,
      };
    }
    return {
      outcome: 'failed',
      httpStatus: res.status,
      serverTs,
      error: body.slice(0, 2000),
      retryable: true,
    };
  } catch (err) {
    return {
      outcome: 'failed',
      httpStatus: null,
      serverTs: null,
      error: err instanceof Error ? err.message : String(err),
      retryable: true,
    };
  }
};

/**
 * Insert a row that is believed not to exist in the cloud yet.
 *
 * Deliberately NOT an upsert: the whole point is to find out whether the row
 * is already there. A duplicate-key rejection is the answer "it exists", and
 * for a snapshot with no base_version that answer means the snapshot is
 * stale - it was captured before this device had any idea what the cloud
 * held - so it must not be written.
 *
 * This single rule is what fixes the observed incident. On the reference
 * install every one of the 796 queued product `create` entries and all 19
 * `delete` entries carry base_version = NULL, and the cloud already holds 595
 * of those products; under the old code each of those entries overwrote a
 * live cloud row with a months-old snapshot.
 */
export const insertIfAbsent = async (
  table: string,
  payload: Record<string, unknown>
): Promise<SupabaseWriteResult> => {
  try {
    const safePayload = await filterToCloudColumns(table, payload);
    const res = await fetch(`${env.supabaseUrl}/rest/v1/${table}`, {
      method: 'POST',
      headers: representationHeaders(),
      body: JSON.stringify([safePayload]),
    });
    const serverTs = serverTimeOf(res);
    if (res.ok) {
      await res.text().catch(() => '');
      return { outcome: 'inserted', httpStatus: res.status, serverTs, retryable: false };
    }
    const body = await res.text().catch(() => res.statusText);

    if (isDuplicateKey(res.status, body)) {
      const remote = await fetchRemoteRow(table, String(payload.id));
      return {
        outcome: 'conflict',
        resolution: 'stale_snapshot_suppressed',
        httpStatus: res.status,
        serverTs,
        error:
          'Snapshot carries no base_version and the row already exists in the cloud; ' +
          'writing it would overwrite whatever has happened to that row since this ' +
          'snapshot was taken. Suppressed.',
        remoteBefore: remote.row,
        remoteVersion: remote.row ? (remote.row.version as number | null) ?? null : null,
        retryable: false,
      };
    }

    if (isMissingTable(res.status, body)) {
      return {
        outcome: 'skipped',
        resolution: 'remote_table_missing',
        httpStatus: res.status,
        serverTs,
        error: `Table "${table}" does not exist in Supabase yet: ${body.slice(0, 500)}`,
        retryable: false,
      };
    }

    return {
      outcome: 'failed',
      httpStatus: res.status,
      serverTs,
      error: body.slice(0, 2000),
      retryable: true,
    };
  } catch (err) {
    return {
      outcome: 'failed',
      httpStatus: null,
      serverTs: null,
      error: err instanceof Error ? err.message : String(err),
      retryable: true,
    };
  }
};

/**
 * Compare-and-swap update for a value entity.
 *
 * Order of events, and why:
 *   1. PATCH ?id=eq.X&version=eq.<base>  → 1 row back means applied. Done.
 *   2. 0 rows back is ambiguous. Read the remote row to find out which of the
 *      three possible worlds we are in - and read it *now*, because by the
 *      time a human looks at the journal it will have moved again.
 *   3. Row absent          → it was never pushed (or was deleted). Insert it.
 *   4. Row present, version NULL → the cloud row predates version control
 *      entirely. Adopt it once, under `version=is.null`, which is itself a
 *      compare-and-swap: if two devices race to adopt, exactly one wins and
 *      the other falls through to a normal conflict.
 *   5. Row present with a different version → a genuine conflict. Nothing is
 *      written. The local value stays in the journal, fully reconstructable,
 *      awaiting a decision.
 *
 * Step 5 deliberately does NOT fall back to overwriting. "Last writer wins
 * after a failed check" is the same silent loss as before, with extra steps
 * and a comforting log line - which is worse than no conflict handling at
 * all, because it looks like it is being handled.
 */
export const conditionalUpdate = async (
  table: string,
  id: string,
  baseVersion: number,
  newVersion: number,
  payload: Record<string, unknown>
): Promise<SupabaseWriteResult> => {
  const body = { ...payload, version: newVersion };
  try {
    const res = await fetch(
      `${env.supabaseUrl}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}&version=eq.${baseVersion}`,
      { method: 'PATCH', headers: representationHeaders(), body: JSON.stringify(body) }
    );
    const serverTs = serverTimeOf(res);

    if (res.ok) {
      const rows = (await res.json().catch(() => [])) as unknown[];
      if (Array.isArray(rows) && rows.length > 0) {
        return { outcome: 'applied', httpStatus: res.status, serverTs, retryable: false };
      }
      // Zero rows affected - not an error, a failed precondition.
      const remote = await fetchRemoteRow(table, id);

      if (remote.ok && remote.row === null) {
        return insertIfAbsent(table, body);
      }

      if (!remote.ok) {
        // Could not read back. Treat as retryable rather than guessing; the
        // one thing we must not do is assume it was fine.
        return {
          outcome: 'failed',
          httpStatus: res.status,
          serverTs,
          error:
            'Conditional update affected 0 rows and the remote row could not be read back ' +
            'to determine why. Left pending for retry.',
          retryable: true,
        };
      }

      const remoteVersion = (remote.row?.version as number | null | undefined) ?? null;

      if (remoteVersion === null || remoteVersion === undefined) {
        const adopt = await fetch(
          `${env.supabaseUrl}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}&version=is.null`,
          { method: 'PATCH', headers: representationHeaders(), body: JSON.stringify(body) }
        );
        const adoptTs = serverTimeOf(adopt);
        if (adopt.ok) {
          const adopted = (await adopt.json().catch(() => [])) as unknown[];
          if (Array.isArray(adopted) && adopted.length > 0) {
            return {
              outcome: 'applied',
              resolution: 'adopted_unversioned',
              httpStatus: adopt.status,
              serverTs: adoptTs,
              remoteBefore: remote.row,
              remoteVersion: null,
              retryable: false,
            };
          }
        } else {
          await adopt.text().catch(() => '');
        }
        // Someone adopted it between our read and our write. Fall through to
        // a conflict with a re-read, rather than trying again in a loop.
        const reread = await fetchRemoteRow(table, id);
        return {
          outcome: 'conflict',
          resolution: null,
          httpStatus: adopt.status,
          serverTs: adoptTs,
          error:
            'Cloud row was unversioned but was claimed by another writer before this ' +
            'device could adopt it.',
          remoteBefore: reread.row ?? remote.row,
          remoteVersion: (reread.row?.version as number | null) ?? null,
          retryable: false,
        };
      }

      return {
        outcome: 'conflict',
        resolution: null,
        httpStatus: res.status,
        serverTs,
        error:
          `Precondition failed: this device believed the cloud row was at version ` +
          `${baseVersion}, but it is at version ${remoteVersion}. Someone else wrote to ` +
          `it in between. Nothing was written; the local value is preserved in this ` +
          `journal entry.`,
        remoteBefore: remote.row,
        remoteVersion,
        retryable: false,
      };
    }

    const text = await res.text().catch(() => res.statusText);

    if (isMissingTable(res.status, text)) {
      return {
        outcome: 'skipped',
        resolution: 'remote_table_missing',
        httpStatus: res.status,
        serverTs,
        error: `Table "${table}" does not exist in Supabase yet: ${text.slice(0, 500)}`,
        retryable: false,
      };
    }

    return {
      outcome: 'failed',
      httpStatus: res.status,
      serverTs,
      error: text.slice(0, 2000),
      retryable: true,
    };
  } catch (err) {
    return {
      outcome: 'failed',
      httpStatus: null,
      serverTs: null,
      error: err instanceof Error ? err.message : String(err),
      retryable: true,
    };
  }
};

/**
 * Deletes are conditional too when a base version is available. Removing a
 * row that someone else has just edited is exactly as destructive as
 * overwriting it, and is harder to notice afterwards because there is no row
 * left to compare against.
 */
export const conditionalDelete = async (
  table: string,
  id: string,
  baseVersion: number | null,
  versioned: boolean
): Promise<SupabaseWriteResult> => {
  const guard = versioned && baseVersion !== null ? `&version=eq.${baseVersion}` : '';
  try {
    const res = await fetch(
      `${env.supabaseUrl}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}${guard}`,
      { method: 'DELETE', headers: representationHeaders() }
    );
    const serverTs = serverTimeOf(res);

    if (res.ok) {
      const rows = (await res.json().catch(() => [])) as unknown[];
      if (!guard || (Array.isArray(rows) && rows.length > 0)) {
        return { outcome: 'applied', httpStatus: res.status, serverTs, retryable: false };
      }
      const remote = await fetchRemoteRow(table, id);
      if (remote.ok && remote.row === null) {
        // Already gone. A delete that finds nothing to delete has achieved
        // its purpose; this is what makes a retried delete idempotent.
        return { outcome: 'applied', httpStatus: res.status, serverTs, retryable: false };
      }
      return {
        outcome: 'conflict',
        resolution: null,
        httpStatus: res.status,
        serverTs,
        error:
          `Delete precondition failed: expected version ${baseVersion}, cloud is at ` +
          `${(remote.row?.version as number | null) ?? 'unknown'}. The row was edited ` +
          `elsewhere after this device decided to delete it. Nothing was deleted.`,
        remoteBefore: remote.row,
        remoteVersion: (remote.row?.version as number | null) ?? null,
        retryable: false,
      };
    }

    const text = await res.text().catch(() => res.statusText);
    if (isMissingTable(res.status, text)) {
      return {
        outcome: 'skipped',
        resolution: 'remote_table_missing',
        httpStatus: res.status,
        serverTs,
        error: `Table "${table}" does not exist in Supabase yet: ${text.slice(0, 500)}`,
        retryable: false,
      };
    }
    return {
      outcome: 'failed',
      httpStatus: res.status,
      serverTs,
      error: text.slice(0, 2000),
      retryable: true,
    };
  } catch (err) {
    return {
      outcome: 'failed',
      httpStatus: null,
      serverTs: null,
      error: err instanceof Error ? err.message : String(err),
      retryable: true,
    };
  }
};

/**
 * Chooses and performs the right write for one outbox entry.
 *
 * This lives here rather than inline in the push loop so that the decision -
 * which is the whole of the conflict scheme - can be exercised directly by
 * tests against a stub PostgREST, without standing up Fastify, JWT auth and
 * a real cloud project. The push loop is then only queue bookkeeping.
 */
export const writeOutboxEntry = async (params: {
  table: string;
  entityType: string;
  opType: 'create' | 'update' | 'delete';
  entityId: string;
  baseVersion: number | null;
  /** Mapped Supabase payload; ignored for deletes. */
  payload: Record<string, unknown> | null;
  /** Local `version` after the change, from the outbox snapshot. */
  localVersion: number | null;
  mode: 'value' | 'ledger';
}): Promise<SupabaseWriteResult> => {
  const { table, opType, entityId, baseVersion, payload, localVersion, mode } = params;

  if (opType === 'delete') {
    const versioned = mode === 'value' && (await supportsVersionColumn(table));
    return conditionalDelete(table, entityId, baseVersion, versioned);
  }

  if (!payload) {
    return {
      outcome: 'skipped',
      resolution: 'no_mapping',
      httpStatus: null,
      serverTs: null,
      error: `No payload mapping for entity_type "${params.entityType}"`,
      retryable: false,
    };
  }

  if (mode === 'ledger') {
    // Append-only record on a stable client-generated id. The unconditional
    // upsert IS the correctness property: it is what makes a retried push
    // converge on one row instead of duplicating. Left exactly as it was.
    return upsertUnconditional(table, payload, 'applied');
  }

  if (!(await supportsVersionColumn(table))) {
    // Migration not applied yet. Behave exactly as before so the working push
    // path does not break, but record that this write went out unguarded.
    return upsertUnconditional(table, payload, 'applied_unguarded');
  }

  if (baseVersion === null || baseVersion === undefined) {
    // No precondition available: a 'create', or anything the backfill sweep
    // produced. May be months old. Allowed to create, forbidden to overwrite.
    return insertIfAbsent(table, payload);
  }

  return conditionalUpdate(
    table,
    entityId,
    baseVersion,
    typeof localVersion === 'number' ? localVersion : baseVersion + 1,
    payload
  );
};

/**
 * Best-effort mirror of a journal row into the cloud journal.
 *
 * A journal that lives only on the device is weak evidence for exactly the
 * scenario it is meant to diagnose: if the till that lost a write is the till
 * that dies, so does the only record that the write ever existed. It is also
 * structurally blind to the multi-till case - device A's journal cannot show
 * you device B's write.
 *
 * It is best-effort, and it is upserted on (device_id, outbox_id), which
 * makes it idempotent under retry and simultaneously turns the cloud journal
 * into the server-side record of which outbox entries have already been
 * applied. Failure here never affects the data write that has already
 * happened - it only means `remote_journaled` stays 0 for that row, which is
 * itself recorded, so the blind spot is visible rather than assumed away.
 */
export const mirrorJournalRows = async (rows: Record<string, unknown>[]): Promise<boolean> => {
  if (rows.length === 0) return true;
  try {
    const res = await fetch(`${env.supabaseUrl}/rest/v1/sync_journal`, {
      method: 'POST',
      headers: { ...upsertHeaders(), Prefer: 'resolution=merge-duplicates' },
      body: JSON.stringify(rows),
    });
    if (!res.ok) {
      await res.text().catch(() => '');
      return false;
    }
    return true;
  } catch {
    return false;
  }
};
